### PR TITLE
New default map

### PR DESCRIPTION
**Pull request by Koenvh1**
This is a new map, for the default map. 
Also see issue https://github.com/mike-koch/ets2-mobile-route-advisor/issues/91

### CODE REVIEW

**Comment by mike-koch** [comment]
Any chance you would like to add the city labels to the map, since we have the JSON for it?  If you don't want to / don't know how, that's fine. I'll create a separate branch and merge your changes in there.

**Comment by Koenvh1** [comment]
@mike-koch I did, but there is one small problem: It tries to download the flag SVG instead of displaying it.

**Comment by mike-koch** [comment]
If the flags aren't displaying properly, they can simply be removed.  I saw your "Added flags layer" commit, and I saw that you added the icons separately. Did adding that separate layer work?

**Comment by Koenvh1** [comment]
Yes, because that way it doesn't have to be a unicode character. 
http://denilson.sa.nom.br/ets2-stuff/openlayers-koenvh1.html also shows the code I used.

I temporarily added a folder flags_png with PNG flags (from http://365icon.com/icon-styles/ethnic/classic2/), and that works too, but I'd prefer SVG images.

**Comment by mike-koch** [comment]
What are the sizes of the PNGs? If they are larger than the max zoom size of the text layer, then there is nothing to worry about in terms of image size.

**Comment by Koenvh1** [comment]
48×48, so they do not look stretched. Still, I'd prefer SVG. These flags have a slight gloss, whether you like it is up to you... If not, replace them :stuck_out_tongue:

**Comment by Koenvh1** [comment]
Also, there is one thing left to do: Look at all the cities, and move them if necessary. I noticed ProMods's Felixstowe (GB) being more north that the default one, so we'll need to correct that. Same for Hamburg (DE), Dortmund (DE), Nymashamn (SE). Ideally we'd make a list of all the default city locations.

I have noticed that my second computer is too slow for teleporting to all the cities (perhaps a lower resolution would work), and I need my primary computer for other things...

**Comment by mike-koch** [comment]
Does the `cities_default.json` you build hold the correct locations for the default cities?

**Comment by Koenvh1** [comment]
Not yet

**Comment by Koenvh1** [comment]
Now I did... Just one quick thing: Felixstowe still is in the wrong location. Not sure why.

**Comment by mike-koch** [comment]
Thanks :smile_cat: . I'll take a look into Felixstowe soon to see what's up with it.

**Comment by mike-koch** [comment]
Ok, I think there's an issue with where the UK scale begins. I noticed that in-game, when driving from the ferry near Felixstowe, my map icon flies off the map for a bit, and then returns. I have a feeling there is an issue with where the range begins, as part of the UK is being calculated in the primary EU region.

**Comment by mike-koch** [comment]
Alrighty, this looks a bit better:

screen shot 2016-03-22 at 9 29 56 pm

**Comment by mike-koch** [comment]
I'm gonna go ahead and merge this in. The country flags look fine to me :smile:

**Pull request merged**
